name: 壁纸更新

on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * *' # UTC时间的0:30

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH
        env: 
          Sub: ${{secrets.SubKey}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh
          echo "$Sub" > ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa

      - name: Set up Git
        run: |
          git config --global user.email "Yuanzhehan@yeah.net"
          git config --global user.name "Tseshongfeeshur"

      - name: Run action.sh
        run: |
          cd ${{ github.workspace }}
          chmod +x action.sh
          ./action.sh
