name: 壁纸更新

on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * *' # UTC时间的0:30

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH
        env: 
          Sub: ${{secrets.SubKey}}
        run: |
          md C:\Users\runneradmin\.ssh
          echo "$Sub" > C:\Users\runneradmin\.ssh\id_rsa
          ssh-keyscan github.com >> C:\Users\runneradmin\.ssh\known_hosts
          # attrib +R %USERPROFILE%\.ssh\id_rsa

      - name: Set up Git
        run: |
          git config --global user.email "Yuanzhehan@yeah.net"
          git config --global user.name "Tseshongfeeshur"

      - name: Run action.bat
        run: |
          cd ${{ github.workspace }}
          cmd /c action.bat
